res_label_dict = {
    "HIS": 1,
    "LYS": 2,
    "ARG": 3,
    "ASP": 4,
    "GLU": 5,
    "SER": 6,
    "THR": 7,
    "ASN": 8,
    "GLN": 9,
    "ALA": 10,
    "VAL": 11,
    "LEU": 12,
    "ILE": 13,
    "MET": 14,
    "PHE": 15,
    "TYR": 16,
    "TRP": 17,
    "PRO": 18,
    "GLY": 19,
    "CYS": 20,
} # "MSE": 21

label_res_dict = {
    1: "H",
    2: "K",
    3: "R",
    4: "D",
    5: "E",
    6: "S",
    7: "T",
    8: "N",
    9: "Q",
    10: "A",
    11: "V",
    12: "L",
    13: "I",
    14: "M",
    15: "F",
    16: "Y",
    17: "W",
    18: "P",
    19: "G",
    20: "C",
} # 21: "M"

chi_dict = {
    "ARG": {"chi_1": "CG", "chi_2": "CD", "chi_3": "NE", "chi_4": "CZ"},
    "LYS": {"chi_1": "CG", "chi_2": "CD", "chi_3": "CE", "chi_4": "NZ"},
    "GLN": {"chi_1": "CG", "chi_2": "CD", "chi_3": "OE1"},
    "GLU": {"chi_1": "CG", "chi_2": "CD", "chi_3": "OE1"},
    "MET": {"chi_1": "CG", "chi_2": "SD", "chi_3": "CE"},
    "ASP": {"chi_1": "CG", "chi_2": "OD1"},
    "ILE": {"chi_1": "CG1", "chi_2": "CD1"},
    "HIS": {"chi_1": "CG", "chi_2": "ND1"},
    "LEU": {"chi_1": "CG", "chi_2": "CD1"},
    "ASN": {"chi_1": "CG", "chi_2": "OD1"},
    "PHE": {"chi_1": "CG", "chi_2": "CD1"},
    "PRO": {"chi_1": "CG", "chi_2": "CD"},
    "TRP": {"chi_1": "CG", "chi_2": "CD1"},
    "TYR": {"chi_1": "CG", "chi_2": "CD1"},
    "VAL": {"chi_1": "CG1"},
    "THR": {"chi_1": "OG1"},
    "SER": {"chi_1": "OG"},
    "CYS": {"chi_1": "SG"},
    "GLY": {},
    "ALA": {},
}
