res_label_dict = {
    "HIS": 0,
    "LYS": 1,
    "ARG": 2,
    "ASP": 3,
    "GLU": 4,
    "SER": 5,
    "THR": 6,
    "ASN": 7,
    "GLN": 8,
    "ALA": 9,
    "VAL": 10,
    "LEU": 11,
    "ILE": 12,
    "MET": 13,
    "PHE": 14,
    "TYR": 15,
    "TRP": 16,
    "PRO": 17,
    "GLY": 18,
    "CYS": 19,
    "MSE": 20
}

label_res_dict = {
    0: "H",
    1: "K",
    2: "R",
    3: "D",
    4: "E",
    5: "S",
    6: "T",
    7: "N",
    8: "Q",
    9: "A",
    10: "V",
    11: "L",
    12: "I",
    13: "M",
    14: "F",
    15: "Y",
    16: "W",
    17: "P",
    18: "G",
    19: "C",
    20: "M"
}

chi_dict = {
    "ARG": {"chi_1": "CG", "chi_2": "CD", "chi_3": "NE", "chi_4": "CZ"},
    "LYS": {"chi_1": "CG", "chi_2": "CD", "chi_3": "CE", "chi_4": "NZ"},
    "GLN": {"chi_1": "CG", "chi_2": "CD", "chi_3": "OE1"},
    "GLU": {"chi_1": "CG", "chi_2": "CD", "chi_3": "OE1"},
    "MET": {"chi_1": "CG", "chi_2": "SD", "chi_3": "CE"},
    "ASP": {"chi_1": "CG", "chi_2": "OD1"},
    "ILE": {"chi_1": "CG1", "chi_2": "CD1"},
    "HIS": {"chi_1": "CG", "chi_2": "ND1"},
    "LEU": {"chi_1": "CG", "chi_2": "CD1"},
    "ASN": {"chi_1": "CG", "chi_2": "OD1"},
    "PHE": {"chi_1": "CG", "chi_2": "CD1"},
    "PRO": {"chi_1": "CG", "chi_2": "CD"},
    "TRP": {"chi_1": "CG", "chi_2": "CD1"},
    "TYR": {"chi_1": "CG", "chi_2": "CD1"},
    "VAL": {"chi_1": "CG1"},
    "THR": {"chi_1": "OG1"},
    "SER": {"chi_1": "OG"},
    "CYS": {"chi_1": "SG"},
    "GLY": {},
    "ALA": {},
}
